### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by muthukumarse** [amiya-pattnaik/webdriverIO-with-cucumberBDD#1]
Can anyone help me on this issue?

✘ ✝  ~/Downloads/webdriverIO-with-cucumberBDD-master  nvm --version
0.33.2
 ✝  ~/Downloads/webdriverIO-with-cucumberBDD-master  node --version
v7.9.0
 ✘ ✝  ~/Downloads/webdriverIO-with-cucumberBDD-master  java -version
Picked up _JAVA_OPTIONS: -Xmx512M
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

 ✘ ✝  ~/Downloads/webdriverIO-with-cucumberBDD-master  npm install

> java@0.7.2 install /Users/muthu/Downloads/webdriverIO-with-cucumberBDD-master/node_modules/java
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../../nan/nan.h:196:
../../nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3346:3: note: 'CloneElementAt' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:4490:3: note: 'New' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../../nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3026:3: note: 'SetAccessor' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:897:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:927:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:956:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:983:42: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Number> val = info[0]->ToNumber();
                                         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1019:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1044:40: warning: 'ToNumber' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Number> val = info[0]->ToNumber();
                                       ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:2220:10: note: 'ToNumber' has been explicitly marked
      deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Number> ToNumber() const);
         ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/java.cpp:1263:16: warning: 'TryCatch' is deprecated [-Wdeprecated-declarations]
  v8::TryCatch tryCatch;
               ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:7616:3: note: 'TryCatch' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use isolate version", TryCatch());
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
10 warnings generated.
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
In file included from ../../nan/nan.h:196:
../../nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
  return array->CloneElementAt(GetCurrentContext(), index);
                ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3346:3: note: 'CloneElementAt' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Cloning is not supported.",
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:4490:3: note: 'New' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/javaObject.cpp:1:
In file included from ../src/javaObject.h:10:
In file included from ../src/methodCallBaton.h:5:
In file included from ../src/utils.h:12:
../../nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3026:3: note: 'SetAccessor' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/javaObject.cpp:116:47: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                              ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3662:3: note: 'NewInstance' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/javaObject.cpp:117:18: error: no member named 'SetHiddenValue' in 'v8::Object'
  javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(...
  ~~~~~~~~~~~~~  ^
../src/javaObject.cpp:349:47: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                              ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8.h:3662:3: note: 'NewInstance' has been explicitly marked
      deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/muthu/.node-gyp/7.9.0/include/node/v8config.h:332:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/javaObject.cpp:350:18: error: no member named 'SetHiddenValue' in 'v8::Object'
  javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(...
  ~~~~~~~~~~~~~  ^
5 warnings and 2 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/javaObject.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/muthu/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/muthu/.nvm/versions/node/v7.9.0/bin/node" "/Users/muthu/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/muthu/Downloads/webdriverIO-with-cucumberBDD-master/node_modules/java
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint@>=3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-standard@3.0.1 requires a peer of eslint@>=3.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngtaf4js-cucumber@1.1.0 No repository field.
npm WARN ngtaf4js-cucumber@1.1.0 scripts['tests'] should probably be scripts['test'].

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/muthu/.npm/_logs/2017-12-04T07_20_09_492Z-debug.log

**Comment by jaffamonkey** [comment]
I had same error, and still trying to debug - lets keep each other posted on progress! :)

**Comment by jaffamonkey** [comment]
I managed to get through the installation with the following fix (assuming you are on a mac).  The issue for me (and seems similar to yours) is related to java.

_Ensure you have Java JDK installed (I have v9 running)_
_Ensure you have Xcode installed_
_Set webdriverio version to 4.9.0+ in package.json_

Then run the following from Terminal.

`cd /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
sudo ln -s ./ jre`

Then run npm install, and let me know how you get on with that.

**Comment by amiya-pattnaik** [comment]
Hi,
The error which you are getting is because of the JDBC module. I have tested it on the JDK 1.8 and it works.Try with JDK 1.8 and let me know. If you don't require database module, you can ignore from the package.json. the JDBC module will require if you are intrested to execute queries and fetch data from the database. 
Thanks,Amiya 

    On Saturday, 9 December 2017 5:45 AM, Paul Littlebury <notifications@github.com> wrote:
 

 I managed to get through the installation with the following fix (assuming you are on a mac). The issue for me (and seems similar to yours) is related to java.Ensure you have Java JDK installed (I have v9 running)
Ensure you have Xcode installed
Set webdriverio version to 4.9.0+ in package.jsonThen run the following from Terminal.cd /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home sudo ln -s ./ jreThen run npm install, and let me know how you get on with that.—

**Comment by jaffamonkey** [comment]
All working now @amiya-pattnaik  - nice effort, and appreciated! :)

**Comment by amiya-pattnaik** [comment]
Closing this JDBC addon module installation issue. Please refer to the  jaffamonkey comment to resolve this issue. Or refer to the installation part of my database framework which can be found at https://github.com/amiya-pattnaik/Database-Test-Automation
