### ISSUE TITLE
Cucumber BDD integration with WebdriverIO v5

### ISSUE THREAD

**Issue by Zarmeena** [amiya-pattnaik/webdriverIO-with-cucumberBDD#10]
Can you please let us know if you will you updating this cucumber BDD project for latest version i.e. v5 of webdriverIO.

**Comment by xyngfei** [comment]
@Zarmeena 

Please refer this link - https://github.com/webdriverio/cucumber-boilerplate/issues/250#issuecomment-492205045, you are welcomed to contribute to this project.

**Comment by Zarmeena** [comment]
Thanks for the reference!
