### ISSUE TITLE
Unable to launch test on Mobile. 

### ISSUE THREAD

**Issue by navaneetit09** [amiya-pattnaik/webdriverIO-with-cucumberBDD#13]
Hi,
I am struggling from last few days in setup for appium with webdriverio.

I downloaded webdriverIO-with-cucumberBDD master.
I am able to run test for web on my laptop, but unable to run script on mobile.

Log is as follows:
![image](https://user-images.githubusercontent.com/34676025/68182730-3e90ee00-ffc0-11e9-8d1e-6d7ca4ce4c41.png)

Complete Log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\navkumar13\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test-mobile',
1 verbose cli   '--logLevel=debug' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'pretest-mobile', 'test-mobile', 'posttest-mobile' ]
5 info lifecycle webdriverIO-with-cucumberBDD@1.1.6~pretest-mobile: webdriverIO-with-cucumberBDD@1.1.6
6 info lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: webdriverIO-with-cucumberBDD@1.1.6
7 verbose lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: unsafe-perm in lifecycle true
8 verbose lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: PATH: C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\navkumar13\Desktop\webdriverIO-with-cucumberBDD-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;"C:\Program Files (x86)\Common Files\Oracle\Java\javapath;";C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Box\Box Edit\;"C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32;";C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files\PuTTY\;C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Users\navkumar13\AppData\Local\Android\Sdk\tools;C:\Users\navkumar13\AppData\Local\Android\Sdk\tools\bin;C:\Users\navkumar13\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\navkumar13\.windows-build-tools\python27\;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\navkumar13\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;"C:\Program Files (x86)\Common Files\Oracle\Java\javapath;";C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Box\Box Edit\;"C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32;";C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Program Files\PuTTY\;C:\Users\navkumar13\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\navkumar13\AppData\Local\Microsoft\WindowsApps;C:\Users\navkumar13\AppData\Roaming\npm;C:\Users\navkumar13\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: CWD: C:\Users\navkumar13\Desktop\webdriverIO-with-cucumberBDD-master
10 silly lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: Args: [ '/d /s /c',
10 silly lifecycle   'node node_modules/.bin/wdio ./test/config/suite.appium.conf.js' ]
11 silly lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: Returned: code: 1  signal: null
12 info lifecycle webdriverIO-with-cucumberBDD@1.1.6~test-mobile: Failed to exec test-mobile script
13 verbose stack Error: webdriverIO-with-cucumberBDD@1.1.6 test-mobile: `node node_modules/.bin/wdio ./test/config/suite.appium.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\navkumar13\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid webdriverIO-with-cucumberBDD@1.1.6
15 verbose cwd C:\Users\navkumar13\Desktop\webdriverIO-with-cucumberBDD-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\navkumar13\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-mobile" "--logLevel=debug"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error webdriverIO-with-cucumberBDD@1.1.6 test-mobile: `node node_modules/.bin/wdio ./test/config/suite.appium.conf.js`
22 error Exit status 1
23 error Failed at the webdriverIO-with-cucumberBDD@1.1.6 test-mobile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Could you please suggest, if am missing something.

Regards
Navaneet Kumar

**Comment by martincxx** [comment]
Hi @navaneetit09 First, keep in mind that this boilerplate's mobile capabilities is set for iPhone emulation, which is only possible on Mac Computers.

Comment the iPhone capabilities on the test/config/suite.appium.conf.js  file. Next, uncomment the Android capabilities.
Make sure you have downloaded the chromedriver and that appium and the Virtual device are running.
(It is also good to  install and run appium-doctor to verify if your configuration is ok)

**Comment by amiya-pattnaik** [comment]
Hi @navaneetit09 ,
it seems to be a problem with the windows build tool. Yesterday I updated few packages. Can you please reinstall it and try. if not try to install windows build tool. below are the commands
npm install -g node-gyp

npm install -g --add-python-to-path --production windows-build-tools

**Comment by navaneetit09** [comment]
Hi @amiya-pattnaik ,

Thanks for your reply.
As suggested, I reinstalled and tried, got same error.
Then installed node-gyp and build tool and tried. But still issue is not resolved.
screen shots are attached.
Build tool installation success:
![image](https://user-images.githubusercontent.com/34676025/68854561-4b20ef00-0702-11ea-9512-11ec64c0ff82.png)
 error screen:
![image](https://user-images.githubusercontent.com/34676025/68854615-6a1f8100-0702-11ea-9514-6cfdef93ba5b.png)

**Comment by navaneetit09** [comment]
Hi @martincxx ,
Thanks for your reply.
I also followed the same steps as you mentioned. appium-doctor is also fine it seems:
![image](https://user-images.githubusercontent.com/34676025/68854902-0f3a5980-0703-11ea-9fd3-4a6fcd8faf22.png)

**Comment by navaneetit09** [comment]
Hi @amiya-pattnaik ,
I found one scrpit error:

"scripts": {
		"selenium-postinstall": "node_modules/.bin/selenium-standalone install",
		"selenium-start": "node_modules/.bin/selenium-standalone start",
		"test": "node_modules/.bin/wdio ./test/config/suite.cucumber.conf.js",
		"test-mobile": "**node** node_modules/.bin/wdio ./test/config/suite.appium.conf.js",
		"allure-report": "node_modules/.bin/allure generate --clean ./test/reports/allure-results && allure open",
		"junit-report": "node_modules/.bin/junit-viewer --results=./test/reports/junit-results --save=junit-results.html && open junit-results.html"
	},


for "test-mobile": it should be as "test-mobile": "node_modules/.bin/wdio ./test/config/suite.appium.conf.js",
after remove "node" from scrpit command, issue is resolved.

Now i am trying further sample scripts.

Thanks
Navaneet Kumar

**Comment by navaneetit09** [comment]
Hi @martincxx ,
Could you please elaborate more about your statement:
Make sure you have downloaded the chromedriver and that appium and the Virtual device are running.
i am running emulator and its id  is as adb devices
List of devices attached
emulator-5554   device

I can see: appium -v
1.15.1

and chrome browser is seen on home screen of emulator which is running.
Am i missing something. Do i need to install any seperate chrome driver.?

Thanks
Navnaeet

**Comment by martincxx** [comment]
@navaneetit09 
You can read in more detail [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md)

**Comment by amiya-pattnaik** [comment]
navaneetit09 .. thanks that your issue is resolved. Windows OS is crazy os :-)
refer to the config.js and run you scripts on your desired platform. I tested code both on iOS and Android it works

**Comment by navaneetit09** [comment]
Thank you very much..!
