### ISSUE TITLE
Cannot find any screenshots when test failed

### ISSUE THREAD

**Issue by fedika** [amiya-pattnaik/webdriverIO-with-cucumberBDD#18]
Hi @amiya-pattnaik 

Thank you for your boilerplate project, I use this for my at web.
I have cloned and I found that there is no screenshots when test failed.

I have checked the suite.cucumber.conf.js line 116 there is
`screenshotPath: './test/reports/errorShots/',   // Saves a screenshot to a given path if a command fails.`
but I did not find errorShots folder created and when I created by myself, I find there is no any screenshots when the test failed

I use node version v12.13.0

Thank you

**Comment by amiya-pattnaik** [comment]
Please take the latest boilerplate code for V6 version
