### ISSUE TITLE
Not able to close the browser on completion of first scenario 

### ISSUE THREAD

**Issue by CharuDattPimple** [amiya-pattnaik/webdriverIO-with-cucumberBDD#20]
I want to run multiple scenarios with given statement has case login each time in same feature file . Whenever I execute the code only 1 scenario executes when it went to second scenario it will throw element not found error .
Observation : Browser remains opens with last expected step from first scenario . So when Second scenario given statement started execution it is throwing element not found error .

What I tried to overcome this problem :
beforeScenario: function () {
browser.newSession()
},
afterScenario: function () {
browser.deleteSession()
// browser.closeWindow()
// browser.newSession(capabilities)
// browser.reloadSession();

},

This is throwing me invalid session ID error .
Config : WDIO V5 Cucumber 4.2.1

**Comment by amiya-pattnaik** [comment]
Please take the latest boilerplate code for V6 version
