### ISSUE TITLE
Unable to generate the XML report in correct format. 

### ISSUE THREAD

**Issue by Pavankumar95153** [amiya-pattnaik/webdriverIO-with-cucumberBDD#21]
Unable to generate the XML report in correct format. Even test passes also getting this <![cdata please help me to fix this I'm using cucumber with Wdio v6.

**Comment by amiya-pattnaik** [comment]
Can you please below detals,
1. Which OS you are using
2. what command you use for XML report

**Comment by Pavankumar95153** [comment]
> Can you please below details,
> 1. Which OS you are using
> 2. what command you use for XML report

OS: windows and node 10
Command to generate XML is 

` module.exports = { // ... reporters: [ 'dot', ['junit', { outputDir: './', outputFileFormat: function(options) { // optional return `results-${options.cid}.${options.capabilities}.xml` } }] ], // ... };'

**Comment by amiya-pattnaik** [comment]
this is to generate the junit reports. It will generate the files in the junit format so the CI tools like Jenkins can read it and display the results.

If you need a local junit report on  your local machine, then use `npm run junit-report`

**Comment by Pavankumar95153** [comment]
> this is to generate the junit reports. It will generate the files in the junit format so the CI tools like Jenkins can read it and display the results.
> 
> If you need a local junit report on  your local machine, then use `npm run junit-report`
> this command will read the juint reports from the /test/reports/junit

I'll try again thanks

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know.
