### ISSUE TITLE
Failed at the webdriverIO-with-cucumberBDD@2.0.2 allure:history script.

### ISSUE THREAD

**Issue by Ajayto** [amiya-pattnaik/webdriverIO-with-cucumberBDD#23]
I am getting below error when trying to run a test with npm run test-local

The syntax of the command is incorrect.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverIO-with-cucumberBDD@2.0.2 allure:history: `mkdir -p allure-report/history ./test/reports/allure-results/history && cp -a allure-report/history ./test/reports/allure-results/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverIO-with-cucumberBDD@2.0.2 allure:history script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know.
