### ISSUE TITLE
Query : getting empty string in stepdef

### ISSUE THREAD

**Issue by gtilekar** [amiya-pattnaik/webdriverIO-with-cucumberBDD#24]
Any Idea how do we pass empty value in v7 with cucumber. Below is sample scenario.
I get null for empty example value.I would like to get it as empty string.

Given user login with "<user>" and "<password>"

example:
    | user | password  |
    | 1234 | password1 |
    | 4564 |           |

StepDef:

Given(/^user login with "([^"]*)" and "([^"]*)"$/, function (arg1, arg2) {
    console.log('------->' + arg1 +'  ------->' + arg2)
});

arg2 in second example is returned as null.

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know.
