### ISSUE TITLE
Errors while running the herokuapp feature

### ISSUE THREAD

**Issue by durgasandeep** [amiya-pattnaik/webdriverIO-with-cucumberBDD#26]
Hi,

 I have tried using this framework to understand JS based frameworks, but i am stuck while running the feature files with the below error. I am able to launch the url but interacting with web elements throws an error:
get usernameInput()   { return $('//*[@name="username"]'); }
this.usernameInput.setValue(username);

[chrome 91.0.4472.77 windows #0-0] this.usernameInput.setValue is not a function
[chrome 91.0.4472.77 windows #0-0] TypeError: this.usernameInput.setValue is not a function

Can you please help me with the error if this has got something to do with the versions of the dependencies used?

**Comment by amiya-pattnaik** [comment]
Hi,
The boilerplate repo is updated to V8. Please check and let me know.
