### ISSUE TITLE
Not finding chai.js::should

### ISSUE THREAD

**Issue by ywarnier** [amiya-pattnaik/webdriverIO-with-cucumberBDD#3]
When hacking a little into your example files to avoid error #2, I get to a point where the browser loads and does some of the expected operations, but then fails with the error message
```
Cannot read property 'equal' of undefined
```
I fixed that by adding 2 lines in given.js
```

import { defineSupportCode } from 'cucumber';
import yahooPage from '../pageobjects/yahoo-search.page';
import loginPage from '../pageobjects/ta-login.page';
import chai from 'chai';

defineSupportCode(function({ Given }) {

  // *** belongs to Yahoo serch feature
  Given(/^I am on the search page$/, function() {
    yahooPage.open();
    chai.should();
    browser.getTitle().should.equal('Yahoo Search - Web Search');
  });

  // *** belongs to ta-loging  feature
  Given(/^I am on the phptravels page$/, function() {
    loginPage.open();     // navigating to login page
  });
});
```

...but I'm not sure if that makes sense and whether this is only because I hacked package.json because of issue #2, or this is useful to anyone else.

**Comment by amiya-pattnaik** [comment]
Thanks for you note and adding chai.should(); to make it working. Let me check and investigate why without this line does not work. Anyway thanks for your update.
Closing the ticket.

**Comment by amiya-pattnaik** [comment]
Issue resolved
