### ISSUE TITLE
project doesnt build on windows 10

### ISSUE THREAD

**Issue by ravi005e** [amiya-pattnaik/webdriverIO-with-cucumberBDD#6]
yarn install v1.6.0

C:\Users\rshanker\git\webdriverIO-with-cucumberBDD>node -v
v8.11.1

C:\Users\rshanker\git\webdriverIO-with-cucumberBDD>npm -v
5.6.0

info No lockfile found.
[1/4] Resolving packages...
warning appium > appium-fake-driver > babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
warning appium > appium-fake-driver > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning appium > appium-fake-driver > babel-core > line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
warning node-uuid@1.4.8: Use uuid module instead
warning wdio-browserstack-service > browserstack-local > sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "win32" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/8] ⢀ waiting...
[2/8] ⢀ heapdump: Finished generating code
[3/8] ⠠ v8-debug: stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[4/8] ⠠ v8-profiler: heap_graph_edge.cc
error C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.11.1 | win32 | x64
node-pre-gyp info check checked for "C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz

C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info ok

C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info spawn C:\Python27\python2.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\v8-debug\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rshanker\\.node-gyp\\8.11.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rshanker\\.node-gyp\\8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\rshanker\\.node-gyp\\8.11.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\v8-debug',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\v8-debug\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64 )  else (node "" build --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  debug.cc
  InjectedScriptHost.cc
  win_delay_load_hook.cc
..\src\debug.cc(41): warning C4996: 'v8::Debug::Call': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(195): note: see declaration of 'v8::Debug::Call'
..\src\debug.cc(52): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\debug.cc(57): warning C4996: 'v8::Debug::SendCommand': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(172): note: see declaration of 'v8::Debug::SendCommand'
..\src\debug.cc(78): error C2039: 'GetMirror': is not a member of 'v8::Debug' [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(26): note: see declaration of 'v8::Debug'
..\src\debug.cc(78): error C3861: 'GetMirror': identifier not found [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(71): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\debug.cc(80): warning C4996: 'v8::Debug::GetDebugContext': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  C:\Users\rshanker\.node-gyp\8.11.1\include\node\v8-debug.h(209): note: see declaration of 'v8::Debug::GetDebugContext'
..\src\InjectedScriptHost.cc(99): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug.vcxproj]
  c:\users\rshanker\git\webdriverio-with-cucumberbdd\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64\debug.node --module_name=debug --module_path=C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug\build\debug\v1.0.1\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rshanker\\git\\webdriverIO-with-cucumberBDD\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\rshanker\git\webdriverIO-with-cucumberBDD\node_modules\v8-debug
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok

**Comment by amiya-pattnaik** [comment]
I guess it seems to be specific to windows on the latest node version. You can try with node 6.10 version is a pretty stable version and check. for the latest node LTS version Please try install `node-gyp` which is native addon build tool.  refer to this link for installation on windows .. https://www.npmjs.com/package/node-gyp

Once build tool is installed properly you should be able to proceed.

**Comment by ravi005e** [comment]
sure didn't help

**Comment by amiya-pattnaik** [comment]
try 
npm install node-pre-gyp install --fallback-to-build

it should work. I do have windows machine and lots of  folks uses windows machine and it works for them. not sure what is the issue with your machine.

**Comment by amiya-pattnaik** [comment]
try npm install node-pre-gyp install --fallback-to-build
it should work. I do have windows machine and lots of  folks uses windows machine and it works for them. not sure what is the issue with your machine.

    On Saturday, 12 May, 2018, 6:38:56 PM GMT-5, ravi005e <notifications@github.com> wrote:  
 
 
sure didn't help
