### ISSUE TITLE
How to pass Cucumber tags from command line

### ISSUE THREAD

**Issue by sankalp-gupta** [amiya-pattnaik/webdriverIO-with-cucumberBDD#7]
Hi Amiya,

Hope you are doing good, I am trying to pass cucumber tags from command line but it's not working, I can manipulate configuration file and it works fine, but I want to do it run-time, can you please help me here.

**Comment by amiya-pattnaik** [comment]
If you want to run only specific tests you can mark your features with tags. These tags will be placed before each feature like so:

@Tag
Feature: ...
To run only the tests with specific tag(s) use the --cucumberOpts.tagExpression= parameter 
like:

wdio -- --cucumberOpts.tagExpression='@Tag or @AnotherTag'

**Comment by sankalp-gupta** [comment]
Hi Amiya,

Thanks for the response, I am aware of cucumber tags and related syntax, but it's not working in boiler plate framework, I found below link which says it will not work because boilerplate uses yedda, not sure if it can be fix it somehow or changing it to wdio test runner is the only option:

https://github.com/webdriverio/cucumber-boilerplate/issues/51#issuecomment-232276364

In my project, we have many scenarios and will be running few of them at a time, we don't want to edit configuration file all the time, that's why I am pushing for this, otherwise it works totally fine when I mention the tags in configuration file.

**Comment by amiya-pattnaik** [comment]
Every boilerplate project uses different modules snd that might be applicable to that one
Can you please provide the details like how you are executing from commandline and what you what options you are also passing alone with that

**Comment by sankalp-gupta** [comment]
Below is the command: 

npm run test -- --cucumberOpts.tagExpression='@sanity'

**Comment by amiya-pattnaik** [comment]
instead of npm script, try directly with yourConf.js --cucumberOpts.tagExpression='@sanity'
it should work
